Repository buttahtoast/helm-charts, pull requests merged in 2021-01, with the labels that each got.

#15 [library] Update Template Paths
  charts/library/Chart.yaml
  charts/library/README.md
  charts/library/README.md.gotmpl
  charts/library/templates/utils/_common.tpl
  charts/library/templates/utils/_dicts.tpl
  charts/library/templates/utils/_experimental.tpl
  charts/library/templates/utils/_extras.tpl
  charts/library/templates/utils/_globals.tpl
  charts/library/templates/utils/_lists.tpl
  charts/library/templates/utils/_strings.tpl
  charts/library/templates/values/_all.yaml
  charts/library/templates/values/_common.yaml
  charts/library/templates/values/_globals.yaml
  charts/library/templates/values/extras/_proxy.yaml
  charts/tavern/README.md
Labels: enhancement

#16 [library] Add TZ Parameter & Update CI
  .github/workflows/linter.yml
  .github/workflows/release.yml
  .github/workflows/testing.yml
  .kube-linter.yaml
  charts/library/.helmignore
  charts/library/Chart.yaml
  charts/library/README.md
  charts/library/templates/utils/_extras.tpl
  charts/library/templates/values/_all.yaml
  charts/library/templates/values/_extras.yaml
  charts/tavern/.helmignore
  charts/tavern/.kube-linter.yaml
Labels: enhancement

#17 [houskeeping]: Changelog in contribution guide & helm source
  CONTRIBUTING.md
  charts/csgo/.kube-linter.yaml
  charts/csgo/Chart.yaml
  charts/library/Chart.yaml
  charts/tavern/Chart.yaml
Labels: documentation

#19 [library, tavern, csgo] Bugfixing & Enhancements
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  charts/csgo/.helmignore
  charts/csgo/Chart.yaml
  charts/csgo/README.md
  charts/csgo/templates/bundle.yaml
  charts/csgo/templates/csgo.tpl
  charts/csgo/templates/secret.yaml
  charts/csgo/values.yaml
  charts/library/.helmignore
  charts/library/Chart.yaml
  charts/library/README.md
  charts/library/templates/utils/_common.tpl
  charts/library/templates/utils/_dicts.tpl
  charts/library/templates/utils/_extras.tpl
  charts/library/templates/utils/_globals.tpl
  charts/library/templates/utils/_lists.tpl
  charts/library/templates/utils/_strings.tpl
  charts/tavern/.helmignore
  charts/tavern/Chart.yaml
  charts/tavern/README.md
  charts/tavern/examples/README.md
  charts/tavern/examples/advanced.yaml
  charts/tavern/examples/simple.yaml
  charts/tavern/templates/_tavern.tpl
  charts/tavern/templates/bundle.yaml
  charts/tavern/templates/tavern_tests.yaml
  charts/tavern/values.yaml
Labels: bug, enhancement
